#!/usr/bin/env python3
"""Materialize the Claude bundle from the canonical portable skill (no symlinks)."""
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / '.agents/skills/analyze-logs'
TARGET = ROOT / '.claude/skills/analyze-logs'


def generated_files():
    skill = (SOURCE / 'SKILL.md').read_text(encoding='utf-8')
    front, body = skill.split('---', 2)[1:]
    description = next(line for line in front.splitlines() if line.startswith('description:'))
    wrapper = f'''---
name: analyze-logs
{description}
argument-hint: <question or command> [files...] [options]
allowed-tools: Bash(cargo run:*), Bash(./target/release/log-analyzer:*), Bash(log-analyzer:*), Read, Glob, Grep
context: fork
---

<!-- Generated by scripts/sync-skills.py; edit .agents/skills/analyze-logs instead. -->

Read [the shared investigation workflow](workflow.md) and follow it for the
user's request. All relative resources resolve from this installed skill folder.
Claude permissions and fork context apply only to this wrapper.
'''
    files = {Path('SKILL.md'): wrapper.encode(), Path('workflow.md'): body.lstrip().encode()}
    for path in SOURCE.rglob('*'):
        relative = path.relative_to(SOURCE)
        if path.is_file() and relative != Path('SKILL.md') and relative.parts[0] != 'agents':
            files[relative] = path.read_bytes()
    return files


def sync(check=False):
    files = generated_files()
    existing = {p.relative_to(TARGET) for p in TARGET.rglob('*') if p.is_file()}
    changed = sorted(str(p) for p, data in files.items() if not (TARGET / p).is_file() or (TARGET / p).read_bytes() != data)
    stale = sorted(str(p) for p in existing - files.keys())
    if check:
        if changed or stale:
            raise SystemExit('Claude bundle is stale; run python3 scripts/sync-skills.py: ' + ', '.join(changed + stale))
        return
    for relative in existing - files.keys():
        (TARGET / relative).unlink()
    for relative, data in files.items():
        destination = TARGET / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_bytes(data)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    sync(parser.parse_args().check)
